Repository Sinu-Tech/Galeraxxx-Search-Escape, pull requests merged in 2022-08, with the labels that each got.

#8 Add: Architeture and base classes
  .gitignore
  src/__init__.py
  src/main.py
  src/models/Enemy.py
  src/models/Map.py
  src/models/Player.py
  src/models/__init__.py
  src/models/abstracts/AbstractCharcater.py
  src/models/abstracts/__init__.py
  src/views/__init__.py
  src/views/pygame
Labels: good first issue, feature

#11 Add: criação da matrix 20x20
  requirements.txt
  src/models/Map.py
  src/models/enums/EnumMap.py
  src/models/enums/__init__.py
Labels: feature

#13 Branch ericles milena7
  .gitignore
  requirements.txt
  src/__init__.py
  src/main.py
  src/models/Cell.py
  src/models/Enemy.py
  src/models/Map.py
  src/models/Player.py
  src/models/__init__.py
  src/models/abs_class/AbstractModel.py
  src/models/abs_class/__init__.py
  src/models/abstracts/__init__.py
  src/models/enums/__init__.py
  src/models/maps.py
  src/utils/__init__.py
  src/utils/map_utils.py
Labels: feature

#17 Branch ericles16
  requirements.txt
  src/main.py
  src/models/Enemy.py
  src/models/maps.py
  src/utils/map_utils.py
Labels: feature

#20 Add: Movimentação do jogador completa
  src/main.py
  src/models/Enemy.py
  src/models/maps.py
Labels: feature

#37 Add: Efeitos sonoros
  src/data/click.wav
  src/data/cristais.mp3
  src/main.py
Labels: enhancement
